"""empty message

Revision ID: 946da285c0a4
Revises: 
Create Date: 2017-05-07 23:56:39.329775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946da285c0a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('img_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'img_path')
    # ### end Alembic commands ###
